/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author ruby
 */
public class CheckBox extends javax.swing.JFrame {

    /**
     * Creates new form CheckBox
     */
    public CheckBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbmensajeprincipal = new javax.swing.JLabel();
        Jcbxcebolla = new javax.swing.JCheckBox();
        Jcbxcilantro = new javax.swing.JCheckBox();
        Jcbxpiña = new javax.swing.JCheckBox();
        Jcbxqueso = new javax.swing.JCheckBox();
        Jbtomarorden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLbmensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbmensajeprincipal.setText("QUE LE PONDREMOS A TUS TAQUTOS!!!");

        Jcbxcebolla.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Jcbxcebolla.setText("cebolla");
        Jcbxcebolla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbxcebollaActionPerformed(evt);
            }
        });

        Jcbxcilantro.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Jcbxcilantro.setText("cilantro");
        Jcbxcilantro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbxcilantroActionPerformed(evt);
            }
        });

        Jcbxpiña.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Jcbxpiña.setText("piña");

        Jcbxqueso.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Jcbxqueso.setText("queso");

        Jbtomarorden.setText("TOMAR ORDEN");
        Jbtomarorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtomarordenActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLbmensaje.setText("Tus taquitos van con..........");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jlbmensajeprincipal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jcbxcilantro)
                            .addComponent(Jcbxpiña)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbmensaje)
                            .addComponent(Jcbxqueso)
                            .addComponent(Jcbxcebolla)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(Jbtomarorden)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbmensajeprincipal)
                .addGap(32, 32, 32)
                .addComponent(Jcbxcebolla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jcbxcilantro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jcbxpiña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jcbxqueso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(Jbtomarorden)
                .addGap(18, 18, 18)
                .addComponent(jLbmensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JcbxcebollaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbxcebollaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbxcebollaActionPerformed

    private void JcbxcilantroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbxcilantroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbxcilantroActionPerformed

    private void JbtomarordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtomarordenActionPerformed
      String orden="";
      if(Jcbxcebolla.isSelected()) {
          orden=orden +"con cebolla\n";
          jTextArea1.setText(orden);
      }
            if(Jcbxcilantro.isSelected()) {
          orden=orden +"con cilantro\n";
          jTextArea1.setText(orden);
      }
                  if(Jcbxpiña.isSelected()) {
          orden=orden +"con piña\n";
          jTextArea1.setText(orden);
      }
                        if(Jcbxqueso.isSelected()) {
          orden=orden +"con queso\n";
          jTextArea1.setText(orden);
      }
    }//GEN-LAST:event_JbtomarordenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtomarorden;
    private javax.swing.JCheckBox Jcbxcebolla;
    private javax.swing.JCheckBox Jcbxcilantro;
    private javax.swing.JCheckBox Jcbxpiña;
    private javax.swing.JCheckBox Jcbxqueso;
    private javax.swing.JLabel jLbmensaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlbmensajeprincipal;
    // End of variables declaration//GEN-END:variables
}
