package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ruby
 */
public class ToggleButton extends javax.swing.JFrame {

    /**
     * Creates new form ToggleButton
     */
    public ToggleButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAlimentacion = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tglAgua = new javax.swing.JToggleButton();
        tglLuz = new javax.swing.JToggleButton();
        tglRenta = new javax.swing.JToggleButton();
        lblAgua = new javax.swing.JLabel();
        lblLuz = new javax.swing.JLabel();
        lblRenta = new javax.swing.JLabel();
        txtTotal = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        txtAlimentacion.setText("Alimentacion");
        getContentPane().add(txtAlimentacion);
        txtAlimentacion.setBounds(60, 60, 90, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 60, 64, 22);

        tglAgua.setText("Agua");
        getContentPane().add(tglAgua);
        tglAgua.setBounds(50, 120, 58, 23);

        tglLuz.setText("Luz");
        tglLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglLuzActionPerformed(evt);
            }
        });
        getContentPane().add(tglLuz);
        tglLuz.setBounds(40, 160, 80, 23);

        tglRenta.setText("Renta");
        tglRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglRentaActionPerformed(evt);
            }
        });
        getContentPane().add(tglRenta);
        tglRenta.setBounds(50, 200, 60, 20);

        lblAgua.setText("30");
        getContentPane().add(lblAgua);
        lblAgua.setBounds(190, 120, 50, 16);

        lblLuz.setText("50");
        getContentPane().add(lblLuz);
        lblLuz.setBounds(190, 160, 50, 16);

        lblRenta.setText("100");
        getContentPane().add(lblRenta);
        lblRenta.setBounds(190, 200, 70, 16);

        txtTotal.setText("TOTAL");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal);
        txtTotal.setBounds(160, 260, 72, 23);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 300, 140, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglLuzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglLuzActionPerformed

    private void tglRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglRentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglRentaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
       double alimentacion,luz,agua,renta;
        
        alimentacion = Double.parseDouble(txtAlimentacion.getText());
        agua = Double.parseDouble(tglAgua.getText());
        luz = Double.parseDouble(tglLuz.getText());
        renta = Double.parseDouble(lblRenta.getText());
        
        double valorTotal;
        
        valorTotal = alimentacion;
        
        if (tglAgua.isSelected()) {
            valorTotal = valorTotal+agua;
        }
        
        if (tglLuz.isSelected()) {
            valorTotal = valorTotal+luz;
        }
        
        if (tglRenta.isSelected()) {
            valorTotal = valorTotal+renta;
        }
        
        txtTotal.setText(valorTotal+"");
    }//GEN-LAST:event_txtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToggleButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAgua;
    private javax.swing.JLabel lblLuz;
    private javax.swing.JLabel lblRenta;
    private javax.swing.JToggleButton tglAgua;
    private javax.swing.JToggleButton tglLuz;
    private javax.swing.JToggleButton tglRenta;
    private javax.swing.JLabel txtAlimentacion;
    private javax.swing.JButton txtTotal;
    // End of variables declaration//GEN-END:variables
}
